/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softpackage;

import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author shata
 */
public class hsm extends javax.swing.JFrame {

    /**
     * Creates new form hsm
     */
    public hsm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminlog = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ausertf = new javax.swing.JTextField();
        Apwtf = new javax.swing.JPasswordField();
        Aloginbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        userlog = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Uusertf = new javax.swing.JTextField();
        Upwtf = new javax.swing.JPasswordField();
        Uloginbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        errordb = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        userpage = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        Uapbtn = new javax.swing.JButton();
        Uprbtn = new javax.swing.JButton();
        Udodbtn = new javax.swing.JButton();
        Ulogoutbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        adminpage = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        Adodbtn = new javax.swing.JButton();
        Adrbtn = new javax.swing.JButton();
        Anrbtn = new javax.swing.JButton();
        Alogoutbtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        admitpatient = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        Unametf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Uiidtf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Uectf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Udobtf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Ubgtf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Upidtf = new javax.swing.JTextField();
        Usubmitbtn = new javax.swing.JButton();
        Uclearbtn = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        dischargepatient = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        Upidtf1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Udischargebtn = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        Usrbtn = new javax.swing.JButton();
        Urecordlabel = new javax.swing.JLabel();
        doctorsonduty = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        Udidtf = new javax.swing.JTextField();
        Usearchbtn = new javax.swing.JButton();
        Udodlabel = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        blank = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        useiid = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        usepid = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        edod = new javax.swing.JFrame();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Adidtf = new javax.swing.JTextField();
        Astf = new javax.swing.JTextField();
        Ausbtn = new javax.swing.JButton();
        Assbtn = new javax.swing.JButton();
        Astatuslabel = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        doctorrecords = new javax.swing.JFrame();
        jLabel25 = new javax.swing.JLabel();
        Adrtf = new javax.swing.JTextField();
        Asearchtf = new javax.swing.JButton();
        Asearchlabel = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        admitdoctor = new javax.swing.JFrame();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Anametf = new javax.swing.JTextField();
        Aqtf = new javax.swing.JTextField();
        Adtf = new javax.swing.JTextField();
        Afstf = new javax.swing.JTextField();
        Actf = new javax.swing.JTextField();
        Aaidtf = new javax.swing.JTextField();
        Airbtn = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        useeid = new javax.swing.JDialog();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        adminlog.setSize(new java.awt.Dimension(0, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Password:");

        Aloginbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Aloginbtn.setText("Login");
        Aloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AloginbtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("     ADMIN LOGIN");

        javax.swing.GroupLayout adminlogLayout = new javax.swing.GroupLayout(adminlog.getContentPane());
        adminlog.getContentPane().setLayout(adminlogLayout);
        adminlogLayout.setHorizontalGroup(
            adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminlogLayout.createSequentialGroup()
                .addGroup(adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminlogLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(Aloginbtn))
                    .addGroup(adminlogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ausertf)
                            .addComponent(Apwtf)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        adminlogLayout.setVerticalGroup(
            adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminlogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ausertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Apwtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(Aloginbtn)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("username:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("password:");

        Uloginbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Uloginbtn.setText("Login");
        Uloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UloginbtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("         USER LOGIN");

        javax.swing.GroupLayout userlogLayout = new javax.swing.GroupLayout(userlog.getContentPane());
        userlog.getContentPane().setLayout(userlogLayout);
        userlogLayout.setHorizontalGroup(
            userlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userlogLayout.createSequentialGroup()
                .addGroup(userlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userlogLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(Uloginbtn))
                    .addGroup(userlogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(userlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(userlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Uusertf)
                            .addComponent(Upwtf)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        userlogLayout.setVerticalGroup(
            userlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userlogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(userlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Uusertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49)
                .addGroup(userlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(Upwtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(Uloginbtn)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        errordb.setTitle("Error!");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("The username or password is incorrect");

        javax.swing.GroupLayout errordbLayout = new javax.swing.GroupLayout(errordb.getContentPane());
        errordb.getContentPane().setLayout(errordbLayout);
        errordbLayout.setHorizontalGroup(
            errordbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errordbLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        errordbLayout.setVerticalGroup(
            errordbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errordbLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        Uapbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Uapbtn.setText("Admit patient");
        Uapbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UapbtnActionPerformed(evt);
            }
        });

        Uprbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Uprbtn.setText("Discharge patient");
        Uprbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UprbtnActionPerformed(evt);
            }
        });

        Udodbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Udodbtn.setText("Doctors on duty");
        Udodbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UdodbtnActionPerformed(evt);
            }
        });

        Ulogoutbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ulogoutbtn.setText("Logout");
        Ulogoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UlogoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Udodbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Uapbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Uprbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ulogoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Uprbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(Uapbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Udodbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(Ulogoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("USER CONTROLS");

        javax.swing.GroupLayout userpageLayout = new javax.swing.GroupLayout(userpage.getContentPane());
        userpage.getContentPane().setLayout(userpageLayout);
        userpageLayout.setHorizontalGroup(
            userpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(userpageLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        userpageLayout.setVerticalGroup(
            userpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userpageLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Adodbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Adodbtn.setText("Edit doctors on duty");
        Adodbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdodbtnActionPerformed(evt);
            }
        });

        Adrbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Adrbtn.setText("Doctors records");
        Adrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdrbtnActionPerformed(evt);
            }
        });

        Anrbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Anrbtn.setText("New record");
        Anrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnrbtnActionPerformed(evt);
            }
        });

        Alogoutbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Alogoutbtn.setText("Logout");
        Alogoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlogoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Anrbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adodbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Adrbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(Alogoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Adrbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(Adodbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Anrbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(Alogoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("ADMIN CONTROLS");

        javax.swing.GroupLayout adminpageLayout = new javax.swing.GroupLayout(adminpage.getContentPane());
        adminpage.getContentPane().setLayout(adminpageLayout);
        adminpageLayout.setHorizontalGroup(
            adminpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminpageLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        adminpageLayout.setVerticalGroup(
            adminpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminpageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel11.setText("Name:");

        jLabel12.setText("Insurance ID:");

        jLabel13.setText("Emergency contact:");

        jLabel14.setText("Date of birth:");

        jLabel15.setText("Blood group:");

        jLabel16.setText("Patient ID assigned:");

        Usubmitbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Usubmitbtn.setText("Submit");
        Usubmitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsubmitbtnActionPerformed(evt);
            }
        });

        Uclearbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Uclearbtn.setText("Clear");
        Uclearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UclearbtnActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("    ADMIT PATIENT");

        javax.swing.GroupLayout admitpatientLayout = new javax.swing.GroupLayout(admitpatient.getContentPane());
        admitpatient.getContentPane().setLayout(admitpatientLayout);
        admitpatientLayout.setHorizontalGroup(
            admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admitpatientLayout.createSequentialGroup()
                .addGroup(admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admitpatientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Unametf, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Udobtf, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ubgtf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Uclearbtn)
                                .addGroup(admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Upidtf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(Uectf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Uiidtf, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(admitpatientLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Usubmitbtn))
                    .addGroup(admitpatientLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(admitpatientLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        admitpatientLayout.setVerticalGroup(
            admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admitpatientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Unametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Uiidtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(Uectf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Udobtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Ubgtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Upidtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admitpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usubmitbtn)
                    .addComponent(Uclearbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel17.setText("Patient ID:");

        jLabel18.setText("Comments:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Udischargebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Udischargebtn.setText("Discharge patient");
        Udischargebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UdischargebtnActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("DISCHARGE PATIENT");

        Usrbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Usrbtn.setText("Show record");
        Usrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrbtnActionPerformed(evt);
            }
        });

        Urecordlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout dischargepatientLayout = new javax.swing.GroupLayout(dischargepatient.getContentPane());
        dischargepatient.getContentPane().setLayout(dischargepatientLayout);
        dischargepatientLayout.setHorizontalGroup(
            dischargepatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dischargepatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dischargepatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dischargepatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Upidtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dischargepatientLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Usrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Udischargebtn)
                .addGap(45, 45, 45))
            .addGroup(dischargepatientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Urecordlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dischargepatientLayout.setVerticalGroup(
            dischargepatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dischargepatientLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dischargepatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Upidtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dischargepatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dischargepatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Udischargebtn)
                    .addComponent(Usrbtn))
                .addGap(18, 18, 18)
                .addComponent(Urecordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel19.setText("Doctor's ID:");

        Usearchbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Usearchbtn.setText("Search");
        Usearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsearchbtnActionPerformed(evt);
            }
        });

        Udodlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("DOCTORS ON DUTY");

        javax.swing.GroupLayout doctorsondutyLayout = new javax.swing.GroupLayout(doctorsonduty.getContentPane());
        doctorsonduty.getContentPane().setLayout(doctorsondutyLayout);
        doctorsondutyLayout.setHorizontalGroup(
            doctorsondutyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorsondutyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(doctorsondutyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Udodlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(doctorsondutyLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(Udidtf, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Usearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorsondutyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        doctorsondutyLayout.setVerticalGroup(
            doctorsondutyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorsondutyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(doctorsondutyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Udidtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usearchbtn))
                .addGap(34, 34, 34)
                .addComponent(Udodlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("     Name, Date of Birth, blood group, patient ID cannot be blank!");

        javax.swing.GroupLayout blankLayout = new javax.swing.GroupLayout(blank.getContentPane());
        blank.getContentPane().setLayout(blankLayout);
        blankLayout.setHorizontalGroup(
            blankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blankLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel20)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        blankLayout.setVerticalGroup(
            blankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blankLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("               Insurance ID is already in use.");

        javax.swing.GroupLayout useiidLayout = new javax.swing.GroupLayout(useiid.getContentPane());
        useiid.getContentPane().setLayout(useiidLayout);
        useiidLayout.setHorizontalGroup(
            useiidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(useiidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        useiidLayout.setVerticalGroup(
            useiidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(useiidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("                Patient ID is already in use.");

        javax.swing.GroupLayout usepidLayout = new javax.swing.GroupLayout(usepid.getContentPane());
        usepid.getContentPane().setLayout(usepidLayout);
        usepidLayout.setHorizontalGroup(
            usepidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usepidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        usepidLayout.setVerticalGroup(
            usepidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usepidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel23.setText("Doctor's ID:");

        jLabel24.setText("Status:");

        Astf.setToolTipText("Available/Unavailable/On leave");

        Ausbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ausbtn.setText("Update status");

        Assbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Assbtn.setText("Show status");

        Astatuslabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("DOCTOR'S STATUS");

        javax.swing.GroupLayout edodLayout = new javax.swing.GroupLayout(edod.getContentPane());
        edod.getContentPane().setLayout(edodLayout);
        edodLayout.setHorizontalGroup(
            edodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edodLayout.createSequentialGroup()
                .addGroup(edodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(edodLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(edodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24))
                            .addGap(40, 40, 40)
                            .addGroup(edodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Adidtf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Astf, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(edodLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(Ausbtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Assbtn)))
                    .addGroup(edodLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Astatuslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edodLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        edodLayout.setVerticalGroup(
            edodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edodLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(edodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Adidtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(edodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(Astf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(edodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ausbtn)
                    .addComponent(Assbtn))
                .addGap(18, 18, 18)
                .addComponent(Astatuslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel25.setText("Doctor's ID:");

        Asearchtf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Asearchtf.setText("Search");

        Asearchlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("DOCTOR'S RECORDS");

        javax.swing.GroupLayout doctorrecordsLayout = new javax.swing.GroupLayout(doctorrecords.getContentPane());
        doctorrecords.getContentPane().setLayout(doctorrecordsLayout);
        doctorrecordsLayout.setHorizontalGroup(
            doctorrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorrecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(doctorrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Asearchlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(doctorrecordsLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(Adrtf, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Asearchtf)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorrecordsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        doctorrecordsLayout.setVerticalGroup(
            doctorrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorrecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(doctorrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Adrtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Asearchtf))
                .addGap(18, 18, 18)
                .addComponent(Asearchlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel26.setText("Name:");

        jLabel27.setText("Qualification:");

        jLabel28.setText("Department:");

        jLabel29.setText("Fixed salary:");

        jLabel30.setText("Contact:");

        jLabel31.setText("Assigned ID:");

        Airbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Airbtn.setText("Insert record");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setText("NEW RECORD");

        javax.swing.GroupLayout admitdoctorLayout = new javax.swing.GroupLayout(admitdoctor.getContentPane());
        admitdoctor.getContentPane().setLayout(admitdoctorLayout);
        admitdoctorLayout.setHorizontalGroup(
            admitdoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admitdoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(admitdoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel26))
                .addGap(54, 54, 54)
                .addGroup(admitdoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Airbtn)
                    .addGroup(admitdoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Anametf)
                        .addComponent(Afstf, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(Adtf)
                        .addComponent(Aqtf)
                        .addComponent(Actf, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Aaidtf, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admitdoctorLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        admitdoctorLayout.setVerticalGroup(
            admitdoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admitdoctorLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admitdoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(Anametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admitdoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Aqtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admitdoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(Adtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admitdoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(Afstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admitdoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(Actf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admitdoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aaidtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addComponent(Airbtn)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("      Employee ID is already in use.");

        javax.swing.GroupLayout useeidLayout = new javax.swing.GroupLayout(useeid.getContentPane());
        useeid.getContentPane().setLayout(useeidLayout);
        useeidLayout.setHorizontalGroup(
            useeidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, useeidLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        useeidLayout.setVerticalGroup(
            useeidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(useeidLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("admin login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("user login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("HOSPITAL MANAGEMENT SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AloginbtnActionPerformed
String usr=Ausertf.getText();
String pwd=new String(Apwtf.getPassword());
if(usr.equals(usr)&&pwd.equals(usr))
{
    adminpage.setVisible(true);
}
else
{
    errordb.setVisible(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_AloginbtnActionPerformed

    private void UloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UloginbtnActionPerformed
String usr=Uusertf.getText();
String pwd=new String(Upwtf.getPassword());
if(usr.equals(usr)&&pwd.equals(usr))
{
    userpage.setVisible(true);
}
else
{
    errordb.setVisible(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_UloginbtnActionPerformed

    private void UapbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UapbtnActionPerformed
admitpatient.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_UapbtnActionPerformed

    private void UprbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UprbtnActionPerformed
dischargepatient.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_UprbtnActionPerformed

    private void UdodbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UdodbtnActionPerformed
doctorsonduty.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_UdodbtnActionPerformed

    private void AdodbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdodbtnActionPerformed
edod.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_AdodbtnActionPerformed

    private void AdrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdrbtnActionPerformed
doctorrecords.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_AdrbtnActionPerformed

    private void AnrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnrbtnActionPerformed
admitdoctor.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_AnrbtnActionPerformed

    private void UsubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsubmitbtnActionPerformed
String a=Unametf.getText();
int b=Integer.parseInt(Uiidtf.getText());
int c=Integer.parseInt(Uectf.getText());
String d=Udobtf.getText();
String e=Ubgtf.getText();
int f=Integer.parseInt(Upidtf.getText());
if(Unametf==null||Udobtf==null||Ubgtf==null||Upidtf==null)
{
    blank.setVisible(true);
}        
try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/software","root","shak");
    Statement st=con.createStatement();
    int i=st.executeUpdate("insert into patient values('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"','"+f+"')");
    jLabel39.setText("   record inserted");
}
catch(Exception z){
    System.out.println(z);
}// TODO add your handling code here:
    }//GEN-LAST:event_UsubmitbtnActionPerformed

    private void UclearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UclearbtnActionPerformed
Unametf.setText("");
Uiidtf.setText("");
Uectf.setText("");
Udobtf.setText("");
Ubgtf.setText("");
Upidtf.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_UclearbtnActionPerformed

    private void UdischargebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UdischargebtnActionPerformed
int a=Integer.parseInt(Upidtf1.getText());
        try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/software","root","shak");
    Statement st=con.createStatement();
    int i=st.executeUpdate("delete from patient where(patientid='"+a+"')");
    Urecordlabel.setText("  patient discharged");
}
catch(Exception z){
    System.out.println(z);
}        // TODO add your handling code here:
    }//GEN-LAST:event_UdischargebtnActionPerformed

    private void UsrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrbtnActionPerformed
int a=Integer.parseInt(Upidtf1.getText());
try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/software","root","shak");
    Statement st=con.createStatement();
    ResultSet i=st.executeQuery("select * from patient where(patientid='"+a+"')");
    Urecordlabel.setText(""+i);
}
catch(Exception z){
    System.out.println(z);
}// TODO add your handling code here:
    }//GEN-LAST:event_UsrbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
adminlog.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
userlog.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UlogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UlogoutbtnActionPerformed
this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));        // TODO add your handling code here:
    }//GEN-LAST:event_UlogoutbtnActionPerformed

    private void AlogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlogoutbtnActionPerformed
this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));        // TODO add your handling code here:
    }//GEN-LAST:event_AlogoutbtnActionPerformed

    private void UsearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsearchbtnActionPerformed
int a=Integer.parseInt(Udidtf.getText());
        try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/software","root","shak");
    Statement st=con.createStatement();
    ResultSet i=st.executeQuery("select * from patient where(doctorid='"+a+"')");
    Udodlabel.setText(""+i);
}
catch(Exception z){
    System.out.println(z);
}        // TODO add your handling code here:
    }//GEN-LAST:event_UsearchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hsm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hsm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hsm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hsm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hsm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Aaidtf;
    private javax.swing.JTextField Actf;
    private javax.swing.JTextField Adidtf;
    private javax.swing.JButton Adodbtn;
    private javax.swing.JButton Adrbtn;
    private javax.swing.JTextField Adrtf;
    private javax.swing.JTextField Adtf;
    private javax.swing.JTextField Afstf;
    private javax.swing.JButton Airbtn;
    private javax.swing.JButton Aloginbtn;
    private javax.swing.JButton Alogoutbtn;
    private javax.swing.JTextField Anametf;
    private javax.swing.JButton Anrbtn;
    private javax.swing.JPasswordField Apwtf;
    private javax.swing.JTextField Aqtf;
    private javax.swing.JLabel Asearchlabel;
    private javax.swing.JButton Asearchtf;
    private javax.swing.JButton Assbtn;
    private javax.swing.JLabel Astatuslabel;
    private javax.swing.JTextField Astf;
    private javax.swing.JButton Ausbtn;
    private javax.swing.JTextField Ausertf;
    private javax.swing.JButton Uapbtn;
    private javax.swing.JTextField Ubgtf;
    private javax.swing.JButton Uclearbtn;
    private javax.swing.JTextField Udidtf;
    private javax.swing.JButton Udischargebtn;
    private javax.swing.JTextField Udobtf;
    private javax.swing.JButton Udodbtn;
    private javax.swing.JLabel Udodlabel;
    private javax.swing.JTextField Uectf;
    private javax.swing.JTextField Uiidtf;
    private javax.swing.JButton Uloginbtn;
    private javax.swing.JButton Ulogoutbtn;
    private javax.swing.JTextField Unametf;
    private javax.swing.JTextField Upidtf;
    private javax.swing.JTextField Upidtf1;
    private javax.swing.JButton Uprbtn;
    private javax.swing.JPasswordField Upwtf;
    private javax.swing.JLabel Urecordlabel;
    private javax.swing.JButton Usearchbtn;
    private javax.swing.JButton Usrbtn;
    private javax.swing.JButton Usubmitbtn;
    private javax.swing.JTextField Uusertf;
    private javax.swing.JFrame adminlog;
    private javax.swing.JFrame adminpage;
    private javax.swing.JFrame admitdoctor;
    private javax.swing.JFrame admitpatient;
    private javax.swing.JDialog blank;
    private javax.swing.JFrame dischargepatient;
    private javax.swing.JFrame doctorrecords;
    private javax.swing.JFrame doctorsonduty;
    private javax.swing.JFrame edod;
    private javax.swing.JDialog errordb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JDialog useeid;
    private javax.swing.JDialog useiid;
    private javax.swing.JDialog usepid;
    private javax.swing.JFrame userlog;
    private javax.swing.JFrame userpage;
    // End of variables declaration//GEN-END:variables
}
